### ISSUE TITLE
魅族 pro 6 plus 不能打开授权界面

### ISSUE THREAD

**Issue by guominfang** [CoXier/FloatWindowPermission#7]
魅族 pro 6 plus 不能打开授权界面，
系统Flyme 6.1.0.0A

**Comment by CoXier** [comment]
不好意思，我手里没有 Pro 6 plus 机型。你可以看看那个 settings 页面对应的 activity

**Comment by guominfang** [comment]
魅族的系统是坑~在 flyme 6.2.5之前的版本，就算底层是6.0也不能使用google提供统一的授权界面，还是只能打开魅族自己定制的权限授权界面。

**Comment by CoXier** [comment]
基本上国内的 room 厂商比如：xiaomi, huawei, meizu 都是经过魔改的，所以你需要去手动探测开启权限的 activity 是哪个，然后手动吊起该 activity。
